version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadbb3
    restart: always
    user: "999:999"
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_PASSWORD: 0traClave
      MARIADB_DATABASE: PEPS
    # userns_mode: keep
    volumes:
      - mariadb_datab33:/var/lib/mysql
      - ./Gimnasio.sql:/docker-entrypoint-initdb.d/Gimnasio.sql:ro
    networks:
      - prueba

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminb3
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7103:80
    depends_on:
      - mariadb
    networks:
      - prueba

  python:
    build: .
    container_name: pythonb3
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
        - mariadb
    networks:
      - prueba
  apache:
    build: ./apache
    container_name: apacheb3
    volumes:
      - ./apache/web:/usr/local/apache2/htdocs/
    ports:
      - "6103:80"
    networks:
      - prueba
    depends_on: 
      - python 

networks:
  prueba:
    driver: bridge

volumes:
  mariadb_datab33:
